websecurityserver/urls.py
from django.contrib import admin
from django.urls import path, include
from websecurityapp.views.actividad_views import ListadoActividadesView, CreacionActividadesView, EdicionActividadesView, \
    EliminacionActividadesView, DetallesActividadesView, VetoActividadesView, LevantamientoVetoActividadesView, \
    ListadoActividadesPropiasView
from websecurityapp.views.oferta_views import ListadoOfertaView, CreacionOfertaView, DetallesOfertaView, EdicionOfertaView, \
    EliminacionOfertaView, VetoOfertaView, LevantamientoVetoOfertaView, CierreOfertaView, SolicitudOfertaView, \
    RetiroSolicitudOfertaView, ListadoOfertaPropiaView, ListadoSolicitudPropiaView
from websecurityapp.views.perfil_views import RegistroUsuarioView, DetallesPerfilView, EdicionPerfilView, CreacionAnexoView, \
    EdicionAnexoView, EliminacionAnexoView, DetallesPerfilAjenoView
from websecurityapp.views.sesionactividad_views import SesionActividadComienzo, SesionActividadFinal
from websecurityapp.views.views import EjercicioMock1View, EjercicioMock2View, EjercicioMock3View
from websecurityapp.views.views import HomeView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('ejercicio/mock/1/', EjercicioMock1View.as_view(), name = 'ejercicio_mock_1'),
    path('ejercicio/mock/2/', EjercicioMock2View.as_view(), name = 'ejercicio_mock_2'),
    path('ejercicio/mock/3/', EjercicioMock3View.as_view(), name = 'ejercicio_mock_3'),
    path('sesionactividad/comienzo/<str:identificador>/', SesionActividadComienzo.as_view(), name='sesionactividad_comienzo'),
    path('sesionactividad/final/<str:identificador>/', SesionActividadFinal.as_view(), name = 'sesionactividad_final'),
    path('admin/', admin.site.urls),
    path('usuario/registro/', RegistroUsuarioView.as_view()),
    path('login/', auth_views.LoginView.as_view(template_name='perfil/login.html', redirect_authenticated_user=True), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/')),
    path('', HomeView.as_view(), name = 'home'),
    path('actividad/listado/', ListadoActividadesView.as_view(), name = 'actividad_listado'),
    path('actividad/listado_propio/', ListadoActividadesPropiasView.as_view(), name = 'actividad_listado_propio'),
    path('actividad/creacion/', CreacionActividadesView.as_view(), name='actividad_creacion'),
    path('actividad/edicion/<int:actividad_id>/', EdicionActividadesView.as_view(), name='actividad_edicion'),
    path('actividad/eliminacion/<int:actividad_id>/', EliminacionActividadesView.as_view(), name='actividad_eliminacion'),
    path('actividad/detalles/<int:actividad_id>/', DetallesActividadesView.as_view(), name = 'actividad_detalles'),
    path('actividad/veto/<int:actividad_id>/', VetoActividadesView.as_view(), name='actividad_veto'),
    path('actividad/levantamiento_veto/<int:actividad_id>/', LevantamientoVetoActividadesView.as_view(), name='actividad_levantamiento_veto'),
    path('perfil/detalles/', DetallesPerfilView.as_view(), name = 'perfil_detalles'),
    path('perfil/detalles/<int:usuario_id>/', DetallesPerfilAjenoView.as_view(), name = 'perfil_detalles_ajeno'),
    path('perfil/edicion/', EdicionPerfilView.as_view(), name = 'perfil_edicion'),
    path('oferta/listado/', ListadoOfertaView.as_view(), name='oferta_listado'),
    path('oferta/listado_propio/', ListadoOfertaPropiaView.as_view(), name='oferta_listado_propio'),
    path('oferta/creacion/', CreacionOfertaView.as_view(), name='oferta_creacion'),
    path('oferta/edicion/<int:oferta_id>/', EdicionOfertaView.as_view(), name='oferta_edicion'),
    path('oferta/detalles/<int:oferta_id>/', DetallesOfertaView.as_view(), name='oferta_detalles'),
    path('oferta/eliminacion/<int:oferta_id>/', EliminacionOfertaView.as_view(), name='oferta_eliminacion'),
    path('oferta/veto/<int:oferta_id>/', VetoOfertaView.as_view(), name='oferta_veto'),
    path('oferta/levantamiento_veto/<int:oferta_id>/', LevantamientoVetoOfertaView.as_view(), name='oferta_levantamiento_veto'),
    path('oferta/cierre/<int:oferta_id>/', CierreOfertaView.as_view(), name='oferta_cierre'),
    path('oferta/listado_solicitud_propio/', ListadoSolicitudPropiaView.as_view(), name='oferta_listado_solicitud_propio'),
    path('oferta/solicitud/<int:oferta_id>/', SolicitudOfertaView.as_view(), name='oferta_solicitud'),
    path('oferta/retiro_solicitud/<int:oferta_id>/', RetiroSolicitudOfertaView.as_view(), name='oferta_retiro_solicitud'),
    path('anexo/creacion_edicion/', CreacionAnexoView.as_view(), name = 'anexo_creacion'),
    path('anexo/creacion_edicion/<int:anexo_id>/', EdicionAnexoView.as_view(), name = 'anexo_edicion'),
    path('anexo/eliminacion/<int:anexo_id>/', EliminacionAnexoView.as_view(), name = 'anexo_eliminacion'),
]

websecurityapp/models/perfil_models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.core.validators import RegexValidator



class Usuario(models.Model):
    django_user = models.ForeignKey(User, on_delete = models.CASCADE)
    telefono = models.CharField(max_length = 30, null = True, blank = True, validators=[RegexValidator(regex = '^(\+\d{1,3}\(\d{1,3}\)*)*\d{4,}$', message = 'No sigue el patron')])
    empresa_u_equipo = models.CharField(max_length = 100, null = True, blank = True)
    vetado = models.BooleanField()
    es_admin = models.BooleanField()
    # Para evitar errores de importación circular de clases, se referencia la clase usando <nombre_app>.<clase_entidad>
    actividades_realizadas = models.ManyToManyField('websecurityapp.Actividad')

class Anexo(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
    anexo = models.URLField()

websecurityapp/forms/perfil_forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

class UsuarioForm(forms.Form):
    nombre_usuario = forms.CharField(max_length = 30)
    contrasenna = forms.CharField(max_length = 30, widget = forms.PasswordInput)
    nombre = forms.CharField(max_length = 30)
    apellidos = forms.CharField(max_length = 30)
    email = forms.EmailField(max_length = 50)
    telefono = forms.CharField(max_length = 30, required = False, validators=[RegexValidator(regex = '^(\+\d{1,3}\(\d{1,3}\)*)*\d{4,}$', message = 'No sigue el patron')])
    empresa_u_equipo = forms.CharField(max_length = 100, required = False)

class AnexoForm(forms.Form):
    anexo = forms.URLField(widget=forms.TextInput(attrs={'class': 'form-control'}))

websecurityapp/views/actividad_views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponse, QueryDict, HttpResponseRedirect
from django.views import View
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from websecurityapp.exceptions import UnallowedUserException
from websecurityapp.forms.actividad_forms import ActividadCreacionForm, ActividadEdicionForm, ActividadVetoForm
from websecurityapp.models.actividad_models import Actividad
from websecurityapp.models.perfil_models import Usuario
from websecurityapp.services.actividad_services import crea_actividad, edita_actividad, elimina_actividad, veta_actividad, \
        levanta_veto_actividad, actividad_formulario, listado_actividades, listado_actividades_propias
from websecurityserver.settings import numero_objetos_por_pagina


class ListadoActividadesView(LoginRequiredMixin, View):
    template_name = 'actividad/listado_actividades.html'

    def get(self, request):
        context = {}
        # Se consulta que usuario esta autenticado en este momento
        try:
            usuario = Usuario.objects.get(django_user_id = request.user.id)
        except ObjectDoesNotExist:
            usuario = None
        # Se obtiene el listado de actividades y se pagina
        actividades = listado_actividades(request)
        paginator = Paginator(actividades, numero_objetos_por_pagina)
        page_number = request.GET.get('page')
        page_obj_actividades = paginator.get_page(page_number)
        # Se añaden al contexto las actividades y el usuario y se muestra el listado
        context.update({
            'page_obj_actividades': page_obj_actividades,
            'usuario': usuario,
            # Se incluyen las actividades realizadas por el usuario, para poder marcarlas al mostrar el listado
            'actividades_realizadas': usuario.actividades_realizadas.all(),
            'titulo_pagina': 'Listado de actividades',
        })
        return render(request, self.template_name, context)

class ListadoActividadesPropiasView(LoginRequiredMixin, View):
    template_name = 'actividad/listado_actividades.html'

    def get(self, request):
        context = {}
        # Se consulta que usuario esta autenticado en este momento
        try:
            usuario = Usuario.objects.get(django_user_id = request.user.id)
        except ObjectDoesNotExist:
            usuario = None
        # Se obtiene el listado de actividades propias y se pagina
        actividades = listado_actividades_propias(request)
        paginator = Paginator(actividades, numero_objetos_por_pagina)
        page_number = request.GET.get('page')
        page_obj_actvidades = paginator.get_page(page_number)
        # Se añaden al contexto las actividades y el usuario y se muestra el listado
        context.update({
            'page_obj_actividades': page_obj_actvidades,
            'usuario': usuario,
            'titulo_pagina': 'Mis actividades',
        })
        return render(request, self.template_name, context)

class CreacionActividadesView(LoginRequiredMixin, View):
    # Todas las comprobaciones de permisos de esta vista las realiza el LoginRequiredMixin
    template_name = 'actividad/creacion_actividades.html'

    def get(self, request):
        context = {}
        # Se genera el formulario vacio de la actividad a crear
        form = ActividadCreacionForm()
        # Se mete el formulario en el contexto y las variables para el estilo de validacion
        # ademas de mostrar el formulario
        context.update({
            'form': form, 
            'validated': False, 
            'form_class': 'needs-validation'
        })
        return render(request, self.template_name, context)

    def post(self, request):
        context = {}
        # Se crea un objeto formulario con los paramentros de entrada dados
        form = ActividadCreacionForm(request.POST)
        # Si el formulario es valido, se trata el formulario y se crea la actividad
        if form.is_valid():
            # Se valida el formulario con mas detalle
            form.clean()
            form_data = form.cleaned_data
            # Se inserta el campo autor en el diccionario que representa el formulario
            autor = Usuario.objects.get(django_user_id = request.user.id)
            form_data.update({'autor': autor})
            # Se intenta crear la actividad
            try:
                actividad_creada = crea_actividad(form_data, request)
            # Si hay una excepcion al crear la actividad se permanece en el formulario 
            # y se incluye un mensaje de error
            except Exception as e:
                messages.error(request, 'Se ha producido un error al crear la actividad')
                # Se mete en el contexto el formulario y las variables para el estilo
                context.update({
                    'form': form, 
                    'validated': True, 
                    'form_class': 'was-validated'
                })
                # Se muestra el formulario de creación de la actividad
                return render(request, self.template_name, context)
            # Redirige al los detalles de la actividad con un mensaje de exito
            messages.success(request, 'Se ha creado la actividad con exito')
            return HttpResponseRedirect(reverse('actividad_detalles', kwargs = {'actividad_id': actividad_creada.id}))
        # Si el formulario no es valido
        else:
            # Vuelve al formulario cuando haya un error de validacion
            # Se valida el formulario con mas detalle
            form.clean()
            # Se da un mensaje de error 
            messages.error(request, 'Se ha producido un error al crear la actividad')
            # Se mete en el contexto el formulario y las variables para el estilo
            context.update({
                'form': form, 
                'validated': True, 
                'form_class': 'was-validated'
            })
            # Se muestra el formulario de la creacion de la actividad
            return render(request, self.template_name, context)

class EdicionActividadesView(LoginRequiredMixin, View):
    # Para visitar esta pagina se requiere estar autenticado y ser el autor de la
    # actividad
    # El LoginRequiredMixin comprueba que el usuario esta autenticado
    # Se debe comprobar de forma programatica que el usuario es el autor de la actividad
    template_name = 'actividad/edicion_actividades.html'

    def get(self, request, actividad_id):
        context = {}
        # Se comprueba que existe la actividad
        try:
            actividad = Actividad.objects.get(pk=actividad_id)
        # Si la actividad no existe, se redirige al usuario al listado de actividades
        except ObjectDoesNotExist as e:
            return actividad_no_hallada(request)
        # Si la actividad no está en modo borrador, no se puede editar
        if not actividad.borrador:
            messages.error(request, 'No se puede editar una actividad que no está en modo borrador')
            return HttpResponseRedirect(reverse('actividad_detalles', kwargs = {'actividad_id': actividad_id}))
        # Se comprueba que el usuario es el autor de la actividad
        # Si el usuario no es el autor de la actividad, se redirige al usuario a la 
        # página de los detalles de la actividad con un mensaje de error
        if not request.user.id == actividad.autor.django_user.id:
            messages.error(request, 'No se poseen los permisos necesarios para editar la actividad')
            return HttpResponseRedirect(reverse('actividad_detalles', kwargs = {'actividad_id': actividad_id}))
        # Se genera un formulario en base a los datos de la actividad
        form = actividad_formulario(actividad)
        # Se mete el formulario y las variables de estilo en el contexto, además de
        # la id de la actividad para el atributo action del formulario
        context.update({
            'actividad_id': actividad_id, 
            'form': form, 
            'validated': False, 
            'form_class': 'needs-validation'
        })
        # Se muestra el formulario de edición de la actividad
        return render(request, self.template_name, context)

    def post(self, request, actividad_id):
        context = {}
        # Comprueba que la actividad existe
        try:
            actividad = Actividad.objects.get(pk=actividad_id)
        # Si no existe la actividad, redirige al usuario al listado de actividades
        except ObjectDoesNotExist as e:
            return actividad_no_hallada(request)
        # Si la actividad no está en modo borrador, no se puede editar
        if not actividad.borrador:
            messages.error(request, 'No se puede editar una actividad que no está en modo borrador')
            return HttpResponseRedirect(reverse('actividad_detalles', kwargs = {'actividad_id': actividad_id}))
        # Se comprueba que el usuario es el autor de la actividad
        # Si el usuario no es el autor de la actividad, se redirige al usuario a la
        # página de los detalles de la actividad con un mensaje de error
        if not request.user.id == actividad.autor.django_user.id:
            messages.error(request, 'No se poseen los permisos necesarios para editar la actividad')
            return HttpResponseRedirect(reverse('actividad_detalles', kwargs = {'actividad_id': actividad_id}))
        # Se crea un objeto formulario en base a los datos recibidos
        form = ActividadEdicionForm(request.POST)
        # Si el formulario es valido, se trata el formulario y se edita la actividad
        if form.is_valid():
            # Se trata el formulario con más detalle
            form.clean()

websecurityapp/views/views.py
from django.shortcuts import render
from django.http import HttpResponse, QueryDict, HttpResponseRedirect
from django.views import View
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.urls import reverse

from websecurityapp.exceptions import UnallowedUserException
from websecurityapp.models.perfil_models import Usuario

# Create your views here.

class HomeView(View):
    template_name = 'master_page/master_page.html'
    
    def get(self, request):
        context = {}
        user = request.user
        if user:
            context.update({
                'user': user,
                'home': True,
            })
        return render(request, self.template_name, context)

class EjercicioMock1View(View):
    template_name = 'utils/ejercicio_mock_1.html'

    def get(self, request):
        return render(request, self.template_name, {})

class EjercicioMock2View(View):
    template_name = 'utils/ejercicio_mock_2.html'

    def get(self, request):
        return render(request, self.template_name, {})

class EjercicioMock3View(View):
    template_name = 'utils/ejercicio_mock_3.html'

    def get(self, request):
        return render(request, self.template_name, {})



    
    

websecurityapp/templates/perfil/detalles_perfil.html
{% extends "master_page/master_page.html" %}

{% block title %}Perfil de {{ usuario_perfil.django_user.username }}{% endblock %}

{% block body %}

    <div id='id_body_detalles_perfil'>

        <p>Nombre : {{ usuario_perfil.django_user.first_name }}</p>
        <p>Apellidos : {{ usuario_perfil.django_user.last_name }}</p>
        <p>Email : {{ usuario_perfil.django_user.email }}</p>
        <p>Telefono : {{ usuario_perfil.telefono }}</p>
        <p>Empresa/equipo : {{ usuario_perfil.empresa_u_equipo }}</p>

        <fieldset id='id_fieldset_anexos'><legend>Anexos</legend>
            <ul>
                {% for anexo in anexos %}
                    <li>
                        <a href="{{ anexo.anexo }}">{{ anexo.anexo }}</a>
                        {% if usuario == usuario_perfil %}
                            <br>
                            <button id="id_boton_edicion_anexo_{{anexo.id}}" onclick="window.location.href = '/anexo/creacion_edicion/{{ anexo.id }}/'">Editar anexo</button>
                            <button id="id_boton_eliminacion_anexo_{{anexo.id}}" onclick="window.location.href = '/anexo/eliminacion/{{ anexo.id }}/'">Eliminar anexo</button>
                        {% endif %}
                    </li>
                    <br>
                {% endfor %}
            </ul>
            {% if usuario == usuario_perfil %}
                <button id="id_boton_creacion_anexo" onclick="window.location.href = '/anexo/creacion_edicion/'">Crear nuevo anexo</button>
            {% endif %}
        </fieldset>

        <fieldset id='id_fieldset_actividades'><legend>Listado de actividades resueltas por {{ usuario_perfil.django_user.username}}</legend>
            {% include 'blocks/lista_listado_actividades.html' with page_obj_actividades=page_obj_actividades_realizadas usuario=usuario page_param='page' mostrar_actividades_vetadas=True %}
        </fieldset>

    </div>

{% endblock %}

websecurityapp/templates/perfil/edicion_perfil.html
{% extends "master_page/master_page.html" %}

{% block title %}Edicion de perfil{% endblock %}

{% block body %}

    <div>

        <form method="post" action="/perfil/edicion/">
            {% csrf_token %}
            {# Include the hidden fields #}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {# Include the visible fields #}
            {% include 'blocks/input_text.html' with type='text' field=form.nombre_usuario was_validated=validated id='id_nombre_usuario' %}
            {% include 'blocks/input_text.html' with type='password' field=form.contrasenna was_validated=validated id='id_contrasenna' %}
            {% include 'blocks/input_text.html' with type='text' field=form.nombre was_validated=validated id='id_nombre' %}
            {% include 'blocks/input_text.html' with type='text' field=form.apellidos was_validated=validated id='id_apellidos' %}
            {% include 'blocks/input_text.html' with type='text' field=form.email was_validated=validated id='id_email' %}
            {% include 'blocks/input_text.html' with type='text' field=form.telefono was_validated=validated id='id_telefono' %}
            {% include 'blocks/input_text.html' with type='text' field=form.empresa_u_equipo was_validated=validated id='id_empresa_u_equipo' %}
            <input type="submit" value="Editar mi perfil" />
        </form>

    </div>

{% endblock %}

websecurityapp/templates/perfil/formulario_anexo.html
{% extends "master_page/master_page.html" %}

{% block title %}
    
    {% if anexo_id %}
        Edición de anexo
    {% else %}
        Creación de anexo
    {% endif %}

{% endblock %}

{% block body %}

    <div>

        {% if anexo_id %}
            <form method="post" action="/anexo/creacion_edicion/{{anexo_id}}/">
        {% else %}
            <form method="post" action="/anexo/creacion_edicion/">
        {% endif %}
            {% csrf_token %}
            {# Include the hidden fields #}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {# Include the visible fields #}
            {% include 'blocks/input_text.html' with type='text' field=form.anexo was_validated=validated id='id_anexo' %}
            <input type="submit" value="Editar el anexo" />
        </form>

    </div>

{% endblock %}

websecurityapp/templates/perfil/login.html
{% extends "master_page/master_page.html" %}

{% block title %}Login{% endblock %}

{% block body %}

    {% if form.errors %}

        <div class="alert alert-danger" role="alert">
            No se ha encontrado un usuario con las credenciales introducidas
        </div>

    {% endif %}

    <div>

        <form action="/login/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login" />
            <input type="hidden" name="next" value="/">
        </form>

    </div>

{% endblock %}

websecurityapp/templates/perfil/registro_usuario.html
{% extends "master_page/master_page.html" %}

{% block title %}Registro de usuario{% endblock %}

{% block body %}   

    {% if registro_exito %}

        <div class="alert alert-success" role="alert">
            Usuario registrado con exito
        </div>

    {% elif registro_exito == False %}

        <div class="alert alert-danger" role="alert">
            No se ha podido registrar al usuario
        </div>

    {% endif %}

    <div>

        <form action="/usuario/registro/" method="post">
            {% csrf_token %}
            {{ usuario_form.as_p }}
            <input type="submit" value="Registrar el usuario" />
        </form>

    </div>

{% endblock %}